# Generated by Django 5.0.6 on 2024-05-24 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(default='', max_length=150)),
                ('email_funcionario', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(default='', max_length=150)),
                ('autor_livro', models.CharField(default='', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(default='', max_length=150)),
                ('email_usuario', models.EmailField(default='', max_length=100)),
            ],
        ),
    ]
