# Generated by Django 5.0.6 on 2024-05-24 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='fone_funcionario',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='livro',
            name='edicao',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='livro',
            name='quantidade_exemplares',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='usuario',
            name='fone_usuario',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='usuario',
            name='idade_usuario',
            field=models.IntegerField(default=0),
        ),
    ]
