# Generated by Django 5.0.6 on 2024-05-24 15:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_funcionario_fone_funcionario_livro_edicao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='cpf_funcionario',
            field=models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AddField(
            model_name='usuario',
            name='cpf_usuario',
            field=models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')]),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='fone_funcionario',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='fone_usuario',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX) XXXX-XXXX ou (XX) XXXXX-XXXX', regex='^\\(\\d{2}\\) \\d{4,5}-\\d{4}$')]),
        ),
    ]
