# Generated by Django 5.0.6 on 2024-05-31 18:05

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id_aluno', models.AutoField(primary_key=True, serialize=False)),
                ('nome_aluno', models.CharField(default='', max_length=150)),
                ('cpf_aluno', models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('fone_aluno', models.CharField(default='(00)00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')])),
                ('email_aluno', models.EmailField(default='', max_length=100)),
                ('idade_aluno', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id_funcionario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_funcionario', models.CharField(default='', max_length=150)),
                ('cpf_funcionario', models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('fone_funcionario', models.CharField(default='(00)00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')])),
                ('email_funcionario', models.EmailField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id_livro', models.AutoField(primary_key=True, serialize=False)),
                ('nome_livro', models.CharField(default='', max_length=150)),
                ('autor_livro', models.CharField(default='', max_length=150)),
                ('edicao', models.IntegerField(default=1)),
                ('quantidade_exemplares', models.IntegerField(default=0)),
                ('descricao', models.TextField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id_prof', models.AutoField(primary_key=True, serialize=False)),
                ('nome_prof', models.CharField(default='', max_length=150)),
                ('cpf_prof', models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('fone_prof', models.CharField(default='(00)00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')])),
                ('email_prof', models.EmailField(default='', max_length=100)),
                ('idade_prof', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nome_usuario', models.CharField(default='', max_length=150)),
                ('cpf_usuario', models.CharField(default='000.000.000-00', max_length=14, validators=[django.core.validators.RegexValidator(message='O formato do CPF deve ser XXX.XXX.XXX-XX', regex='^\\d{3}\\.\\d{3}\\.\\d{3}-\\d{2}$')])),
                ('fone_usuario', models.CharField(default='(00)00000-0000', max_length=15, validators=[django.core.validators.RegexValidator(message='O formato do telefone deve ser (XX)XXXXX-XXXX', regex='^\\(\\d{2}\\)\\d{4,5}-\\d{4}$')])),
                ('email_usuario', models.EmailField(default='', max_length=100)),
                ('idade_usuario', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aluno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.aluno')),
            ],
        ),
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id_disciplina', models.AutoField(primary_key=True, serialize=False)),
                ('nome_disciplina', models.CharField(default='', max_length=150)),
                ('professor_disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.professor')),
            ],
        ),
        migrations.CreateModel(
            name='Turma',
            fields=[
                ('id_turma', models.AutoField(primary_key=True, serialize=False)),
                ('nome_turma', models.CharField(default='', max_length=150)),
                ('alunos_turma', models.ManyToManyField(through='api_rest.Matricula', to='api_rest.aluno')),
                ('professor_turma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.professor')),
            ],
        ),
        migrations.AddField(
            model_name='matricula',
            name='turma',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_rest.turma'),
        ),
        migrations.AlterUniqueTogether(
            name='matricula',
            unique_together={('aluno', 'turma')},
        ),
    ]
